### ISSUE TITLE
Submit to gazebo_ros_pkgs?

### ISSUE THREAD

**Issue by rethink-imcmahon** [roboticsgroup/roboticsgroup_gazebo_plugins#1]
Hi @costashatz! Great work here implementing Mimic joints, which has been a feature missing from [gazebo_ros_pkgs](https://github.com/ros-simulation/gazebo_ros_pkgs) for quite some time (see https://github.com/ros-simulation/gazebo_ros_pkgs/issues/251).

Do you have any plans to submit your work as a pull request to `gazebo_ros_packages`? They have [aggregated several plugins](https://github.com/ros-simulation/gazebo_ros_pkgs/tree/indigo-devel/gazebo_plugins/include/gazebo_plugins) there already. I think your work would be more widely accessible to the community if it was included in this default package. Also you wouldn't need to go through the work of bloom-releasing it yourself :) Thanks!

**Comment by costashatz** [comment]
Hello and thank you for your interest in our code,

I've been thinking of creating a pull request to `gazebo_ros_pkgs`, but I haven't found the time yet. Also, I am not exactly sure where/how this feature should be used. I can think of 2 possible ways:
- Standalone plugin. Basically the form it has now. I will check for possible optimizations/corrections (I have on in mind already).
- Implement it inside gazebo_ros_control. This should be the best way to implement it, but I don't know if I have the time to implement it at the moment.

What do you think?

**Comment by BenArtes** [comment]
I've re-raised the possibility of pulling your code into gazebo_ros_pkgs.

https://github.com/ros-simulation/gazebo_ros_pkgs/issues/251#issuecomment-537156885

Would you support someone else (potentially me) integrating the plugin into gazebo_ros_pkgs?

**Comment by costashatz** [comment]
> I've re-raised the possibility of pulling your code into gazebo_ros_pkgs.
> 
> [ros-simulation/gazebo_ros_pkgs#251 (comment)](https://github.com/ros-simulation/gazebo_ros_pkgs/issues/251#issuecomment-537156885)

@BenArtes thanks!

> Would you support someone else (potentially me) integrating the plugin into gazebo_ros_pkgs?

Sure! I cannot guarantee free time any period of the year, but when it happens I'll be more than happy to help in integrating our plugins to gazebo_ros_pkgs. Depending on the timeline that the gazebo_ros_pkgs maintainers want, I could possibly initiate it myself (and finish it with some help or vice-versa).

**Comment by BenArtes** [comment]
Awesome!

Merging is straight forward and quick (already merged them in my local repo), just wanted to make sure you were still on board with it. We'll see what the maintainers say, but if you're busy I'm more than happy to manage it for you if you'd like.

(And thanks for the quick response) :smiley: .

**Comment by nlamprian** [comment]
This package has been deprecated. Forward any future requests to [roboticsgroup_upatras_gazebo_plugins](https://github.com/roboticsgroup/roboticsgroup_upatras_gazebo_plugins).
