### ISSUE TITLE
gazebo7: setAngle not possible?

### ISSUE THREAD

**Issue by tianshiz** [roboticsgroup/roboticsgroup_gazebo_plugins#16]
Hi, 

   I'm using the mimic joint on a 4 bar like robotic limb. One particular joint is getting forced apart from internal forces of the limb when it moves. I tried raising the the effort limit and setting the effort of the original joint to huge numbers, but it is not helping.

Is this a PID issue? Or is there some other limitations?

Ideally I'd want performance akin to setAngle, just forcing the angle. But, because of the gazebo bug, it doesn't seem possible?

**Comment by nlamprian** [comment]
I don't know the conditions of your simulation, but this is a general gazebo control problem. It's likely not an issue of the plugin.

When you specify hasPid in your configuration, the plugin does force control. When you don't specify hasPid, the plugin does position control. So, I'd suggest that you remove hasPid and try again. Alternatively, you can keep hasPid, open rqt_reconfigure, and tune the pid (while also tweaking the effort limit).

**Comment by tianshiz** [comment]
I tried to remove hasPID and even updated to gazebo9, but my link keeps falling slowly and then quickly snaps back, applying a lot of random force.

Does this plugin work without hasPID in gazebo9+kinetic?

**Comment by nlamprian** [comment]
Yes, it does. I'm using it successfully myself. Unfortunately, I don't have enough information about your simulation to suggest anything else.

**Comment by nlamprian** [comment]
I recently identified and fixed a bug relating to setting the force limit when in position control. You should now be able to set the angle of your mimic joints successfully.
