### ISSUE TITLE
Error while building package with catkin build

### ISSUE THREAD

**Issue by bornaZbodulja** [roboticsgroup/roboticsgroup_gazebo_plugins#18]
Hi,

I'm trying to setup virtual pepper in gazebo, therefor I need to build this package. Running catkin build on this package throws this error:

In file included from /usr/include/ignition/msgs1/ignition/msgs/color.pb.h:23:0,
                 from /usr/include/gazebo-9/gazebo/msgs/msgs.hh:32,
                 from /usr/include/gazebo-9/gazebo/gazebo_core.hh:20,
                 from /usr/include/gazebo-9/gazebo/gazebo.hh:20,
                 from /home/borna/catkin_ws1/src/roboticsgroup_gazebo_plugins/include/roboticsgroup_gazebo_plugins/mimic_joint_plugin.h:37,
                 from /home/borna/catkin_ws1/src/roboticsgroup_gazebo_plugins/src/mimic_joint_plugin.cpp:18:
/usr/local/include/google/protobuf/arenastring.h:225:31: note: candidate: const string& google::protobuf::internal::ArenaStringPtr::GetNoArena() const
   inline const ::std::string& GetNoArena() const { return *ptr_; }
                               ^~~~~~~~~~
/usr/local/include/google/protobuf/arenastring.h:225:31: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/ignition/msgs1/ignition/msgs/MessageTypes.hh:170:0,
                 from /usr/include/ignition/msgs1/ignition/msgs/Utility.hh:29,
                 from /usr/include/ignition/msgs1/ignition/msgs.hh:25,
                 from /usr/include/ignition/transport4/ignition/transport/Node.hh:32,
                 from /usr/include/gazebo-9/gazebo/physics/Entity.hh:25,
                 from /usr/include/gazebo-9/gazebo/physics/Model.hh:30,
                 from /usr/include/gazebo-9/gazebo/physics/Actor.hh:26,
                 from /usr/include/gazebo-9/gazebo/physics/physics.hh:2,
                 from /home/borna/catkin_ws1/src/roboticsgroup_gazebo_plugins/include/roboticsgroup_gazebo_plugins/mimic_joint_plugin.h:38,
                 from /home/borna/catkin_ws1/src/roboticsgroup_gazebo_plugins/src/mimic_joint_plugin.cpp:18:
/usr/include/ignition/msgs1/ignition/msgs/world_modify.pb.h: In member function ‘const string& ignition::msgs::WorldModify::cloned_uri() const’:
/usr/include/ignition/msgs1/ignition/msgs/world_modify.pb.h:400:93: error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::GetNoArena(const string*) const’
   return cloned_uri_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                                                                                             ^
In file included from /usr/include/ignition/msgs1/ignition/msgs/color.pb.h:23:0,
                 from /usr/include/gazebo-9/gazebo/msgs/msgs.hh:32,
                 from /usr/include/gazebo-9/gazebo/gazebo_core.hh:20,
                 from /usr/include/gazebo-9/gazebo/gazebo.hh:20,
                 from /home/borna/catkin_ws1/src/roboticsgroup_gazebo_plugins/include/roboticsgroup_gazebo_plugins/mimic_joint_plugin.h:37,
                 from /home/borna/catkin_ws1/src/roboticsgroup_gazebo_plugins/src/mimic_joint_plugin.cpp:18:
/usr/local/include/google/protobuf/arenastring.h:225:31: note: candidate: const string& google::protobuf::internal::ArenaStringPtr::GetNoArena() const
   inline const ::std::string& GetNoArena() const { return *ptr_; }

I tried rosdep on package to see if I don't have some installed dependencies, but rosdep throws "All dependencies already installed." My version of gazebo is 9.0 and protoc version is 3.4.0. Looking for possible solution on Internet I think that issue might be that gazebo uses older version of protobuff.

**Comment by costashatz** [comment]
> Looking for possible solution on Internet I think that issue might be that gazebo uses older version of protobuff.

Indeed! I am pretty sure that this is not related to our repository: after all, we are just querying for Gazebo in the CMake and using only very basic functionality (no protobuf or anything).

You might need to install the latest ignition libraries or gazebo from the repository (and not the official releases). Which OS are you using? How did you install protobuf, gazebo, ignition libraries etc?

**Comment by bornaZbodulja** [comment]
Thanks for reply!
I'm using ubuntu 18.04 and I installed gazebo and protobuf with apt-get install. I'll try to reinstall gazebo and install it from source to see if that solves the issue.

**Comment by nlamprian** [comment]
Gazebo expects a specific version of protobuf. Uninstall the version you installed by yourself.

**Comment by costashatz** [comment]
> I'll try to reinstall gazebo and install it from source to see if that solves the issue.

I do not think that this is necessary.

> Gazebo expects a specific version of protobuf. Uninstall the version you installed by yourself.

You should do what @nlamprian says..

**Comment by bornaZbodulja** [comment]
> Gazebo expects a specific version of protobuf. Uninstall the version you installed by yourself.

I think I found the source of the issue. When I was building Cartographer, it installed the newer version of protobuf which has overridden my original version of protobuf. Now I will try to uninstall the version that Cartographer installed. Hope that this is going to solve the issue. Thanks for help!

**Comment by bornaZbodulja** [comment]
Yep, problem solved.
If anyone has the same problem just do this:

git clone https://github.com/google/protobuf.git
cd protobuf
git checkout tags/v3.0.0
mkdir build
cd build
cmake -G Ninja \
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
  -DCMAKE_BUILD_TYPE=Release \
  -Dprotobuf_BUILD_TESTS=OFF \
  ../cmake
ninja
sudo ninja install

Thanks for the help!

**Comment by costashatz** [comment]
> Yep, problem solved.

Great! Thanks for reporting the issue and the solution!
