### ISSUE TITLE
a != a

### ISSUE THREAD

**Issue by Maxx84** [roboticsgroup/roboticsgroup_gazebo_plugins#19]
Hi, thanks for this plugin! 
I'm confused about the expected behavior of these two lines of code:
https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins/blob/master/src/mimic_joint_plugin.cpp#L171-L172

In which situation **a** should not be equal to **a**?

**Comment by costashatz** [comment]
> In which situation **a** should not be equal to **a**?

This is a quick way of checking for NaN values, see [here](https://stackoverflow.com/questions/570669/checking-if-a-double-or-float-is-nan-in-c)...

**Comment by Maxx84** [comment]
Oh, I see! Thanks

**Comment by costashatz** [comment]
> Oh, I see! Thanks

No problem! Closing this issue! Let us know if you have any other question/issue.
