### ISSUE TITLE
is this plugin compatible with ignition gazebo as well?

### ISSUE THREAD

**Issue by addy1997** [roboticsgroup/roboticsgroup_gazebo_plugins#23]

**Comment by nlamprian** [comment]
No, ignition gazebo is not compatible with classic gazebo.

**Comment by addy1997** [comment]
> No, ignition gazebo is not compatible with classic gazebo.

Can I migrate it to ignition gazebo API for my application?

**Comment by nlamprian** [comment]
Yes, that should be possible. You'll find relevant resources on the [ignitionrobotics](https://ignitionrobotics.org/api/gazebo/3.2/tutorials.html) website.
